CREATE TABLE [dbo].[ServiceLineDRG] (
    [ServiceLineId]                        INT                                   NOT NULL,
    [DRG_Columnset]                        XML COLUMN_SET FOR ALL_SPARSE_COLUMNS,
    [PlanID]                               VARCHAR (8) SPARSE                    NULL,
    [PlanID_Name]                          VARCHAR (255) SPARSE                  NULL,
    [Business_Category_Code]               VARCHAR (4) SPARSE                    NULL,
    [Business_Category_Description]        VARCHAR (255) SPARSE                  NULL,
    [Medicare_Facility_Number_BLNG_PROV]   VARCHAR (15) SPARSE                   NULL,
    [HCRA_BLNG_PROV]                       VARCHAR (4) SPARSE                    NULL,
    [Medicare_Facility_Number_SRVCNG_PROV] VARCHAR (15) SPARSE                   NULL,
    [HCRA_SRVCNG_PROV]                     VARCHAR (4) SPARSE                    NULL,
    [Micro_Image_ID]                       VARCHAR (50) SPARSE                   NULL,
    [SCCF_Number]                          VARCHAR (17) SPARSE                   NULL,
    [Plan_Code]                            VARCHAR (4) SPARSE                    NULL,
    [Plan_Code_home]                       VARCHAR (20) SPARSE                   NULL,
    [Additional_Diagnosis_9]               VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_10]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_11]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_12]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_13]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_14]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_15]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_16]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_17]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_18]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_19]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_20]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_21]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_22]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_23]              VARCHAR (7) SPARSE                    NULL,
    [Additional_Diagnosis_24]              VARCHAR (7) SPARSE                    NULL,
    [Additional_proc_code_6]               VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_7]               VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_8]               VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_9]               VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_10]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_11]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_12]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_13]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_14]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_15]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_16]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_17]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_18]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_19]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_20]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_21]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_22]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_23]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_24]              VARCHAR (20) SPARSE                   NULL,
    [Additional_proc_code_25]              VARCHAR (20) SPARSE                   NULL,
    [HCRA_Surcharge_Amount]                MONEY SPARSE                          NULL,
    [Risk_Withhold_Amount]                 MONEY SPARSE                          NULL,
    [PTNT_ACNT_NBR]                        VARCHAR (35) SPARSE                   NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [CL_ServiceLineDRG]
    ON [dbo].[ServiceLineDRG]([ServiceLineId] ASC);

