








CREATE Procedure [dbo].[usp_LoadExcellusServiceLineAdditionalData] ( @DataDate Varchar(7), @FileRequestId  UniqueIdentifier)

as 

BEGIN


IF OBJECT_ID('dbo.AdditionalDataStage', 'U') IS NOT NULL 
BEGIN
DROP TABLE [dbo].[AdditionalDataStage]
END






SELECT 
	CONVERT(NVARCHAR(255),RTRIM(LTRIM(Claim_Number)) +  RTRIM(LTRIM(SRC_APPL_ADJ_SQNC_NBR)))
				as ClaimRepoClaimNumber	
	,CONVERT(NVARCHAR(255),CONVERT(INT,Claim_Line_Number)) 
				as  ClaimRepoClaimLineNumber
,CONVERT(VARCHAR(2) ,[File_Type]) AS [File_Type]
,CONVERT(VARCHAR(8) ,[Claim_Adjustment_Number]) AS [Claim_Adjustment_Number]
,CONVERT(VARCHAR(1) ,[Drug_line]) AS [Drug_line]
,CONVERT(VARCHAR(70) ,[CPT4_Procedure_code_Description]) AS [CPT4_Procedure_code_Description]
,CONVERT(VARCHAR(7) ,[Insurance_Company_Unique_ID]) AS [Insurance_Company_Unique_ID]
,CONVERT(VARCHAR(20) ,[Unique_ID]) AS [Unique_ID]
,CONVERT(VARCHAR(30) ,[Contract_holders_ID]) AS [Contract_holders_ID]
,CONVERT(VARCHAR(3) ,[Dependent_Number]) AS [Dependent_Number]
,CONVERT(MONEY ,[Other_carrier_paid_amt]) AS [Other_carrier_paid_amt]
,CONVERT(MONEY ,[Claim_Member_Liability]) AS [Claim_Member_Liability]
,CONVERT(DATETIME ,[Claim_Paid_Date]) AS [Claim_Paid_Date]
,CONVERT(VARCHAR(7) ,[Admitting_Diagnosis]) AS [Admitting_Diagnosis]
,CONVERT(VARCHAR(20) ,[Additional_proc_code_1]) AS [Additional_proc_code_1]
,CONVERT(VARCHAR(20) ,[Additional_proc_code_2]) AS [Additional_proc_code_2]
,CONVERT(VARCHAR(20) ,[Additional_proc_code_3]) AS [Additional_proc_code_3]
,CONVERT(VARCHAR(20) ,[Additional_proc_code_4]) AS [Additional_proc_code_4]
,CONVERT(VARCHAR(20) ,[Additional_proc_code_5]) AS [Additional_proc_code_5]
,CONVERT(VARCHAR(255) ,[Place_of_Service_Desc]) AS [Place_of_Service_Desc]
,CONVERT(VARCHAR(4) ,[Hosp_Med_Ind]) AS [Hosp_Med_Ind]
,CONVERT(VARCHAR(9) ,[Home_Grown_Code]) AS [Home_Grown_Code]
,CONVERT(VARCHAR(250) ,[Home_Grown_Code_Desc]) AS [Home_Grown_Code_Desc]
,CONVERT(VARCHAR(9) ,[HCPCS_Code]) AS [HCPCS_Code]
,CONVERT(VARCHAR(150) ,[HCPCS_Desc]) AS [HCPCS_Desc]
,CONVERT(VARCHAR(4) ,[Type_of_Service_Code]) AS [Type_of_Service_Code]
,CONVERT(VARCHAR(70) ,[Type_of_Service_Desc]) AS [Type_of_Service_Desc]
,CONVERT(VARCHAR(1) ,[Par_Code]) AS [Par_Code]
,CONVERT(VARCHAR(75) ,[Par_Desc]) AS [Par_Desc]
,CONVERT(VARCHAR(18) ,[Servicing_Provider_Tax_Id]) AS [Servicing_Provider_Tax_Id]
,CONVERT(VARCHAR(70) ,[Adjustment_Indicator]) AS [Adjustment_Indicator]
,CONVERT(VARCHAR(30) ,[Agreement_ID]) AS [Agreement_ID]
,CONVERT(VARCHAR(18) ,[Authorization_Code]) AS [Authorization_Code]
,CONVERT(DECIMAL(19,2),[CLHP_Birth_Wgt]) AS [CLHP_Birth_Wgt]
,CONVERT(VARCHAR(20) ,[Frequency]) AS [Frequency]
,CONVERT(VARCHAR(16) ,[MEDICAL_RECNO]) AS [MEDICAL_RECNO]
,CONVERT(VARCHAR(3) ,[Medicare_DRG_Code]) AS [Medicare_DRG_Code]
,CONVERT(VARCHAR(1) ,[Mem_Cobra_Indicator]) AS [Mem_Cobra_Indicator]
,CONVERT(VARCHAR(12) ,[Mem_Medicare_Number]) AS [Mem_Medicare_Number]
,CONVERT(VARCHAR(30) ,[Mem_Phone]) AS [Mem_Phone]
,CONVERT(VARCHAR(1) ,[Mem_Retirement_Ind]) AS [Mem_Retirement_Ind]
,CONVERT(VARCHAR(4) ,[Rule]) AS [Rule]
,CONVERT(VARCHAR(4) ,[Service_Pricing]) AS [Service_Pricing]
,CONVERT(MONEY ,[Unit_Days_Allowed]) AS [Unit_Days_Allowed]
,CONVERT(VARCHAR(20) ,[DSALW_CODE]) AS [DSALW_CODE]
,CONVERT(VARCHAR(255) ,[DSALW_CODE_DESC]) AS [DSALW_CODE_DESC]
,CONVERT(VARCHAR(20) ,[ADJ_EXPLN_CODE]) AS [ADJ_EXPLN_CODE]
,CONVERT(VARCHAR(255) ,[ADJ_EXPLN_CODE_DESC]) AS [ADJ_EXPLN_CODE_DESC]
,CONVERT(VARCHAR(75) ,[Network_Indicator_Par_Non_Par_System]) AS [Network_Indicator_Par_Non_Par_System]
,CONVERT(VARCHAR(75) ,[Claim_Type]) AS [Claim_Type]
,CONVERT(DATETIME,[Claim_Received_Date]) AS [Claim_Received_Date]
,CONVERT(VARCHAR(75) ,[Payee_Code]) AS [Payee_Code]
,CONVERT(VARCHAR(75) ,[COB_NAME]) AS [COB_NAME]
,CONVERT(VARCHAR(20) ,[Src_appl_code]) AS [SRC_APPL_CODE]
,CONVERT(VARCHAR(5) ,[SRC_APPL_ADJ_SQNC_NBR]) AS [SRC_APPL_ADJ_SQNC_NBR]
,CONVERT(VARCHAR(4) ,[GRP_SGMNT_CODE]) AS [GRP_SGMNT_CODE]
,CONVERT(VARCHAR(255) ,[GRP_SGMNT_CODE_DESC]) AS [GRP_SGMNT_CODE_DESC]
,CONVERT(VARCHAR(20) ,[FAC_TYPE_CODE]) AS [FAC_TYPE_CODE]
,CONVERT(VARCHAR(255) ,[FAC_TYPE_CODE_NAME]) AS [FAC_TYPE_CODE_NAME]
,CONVERT(VARCHAR(255) ,[BSNS_SGMNT]) AS [BSNS_SGMNT]
,CONVERT(VARCHAR(255) ,[PROD_CAT_NAME]) AS [PROD_CAT_NAME]
,CONVERT(VARCHAR(20) ,[DRG_SYS_ID]) AS [DRG_SYS_ID]
,CONVERT(VARCHAR(4) ,[SOI]) AS [SOI]
,CONVERT(VARCHAR(4) ,[ROM]) AS [ROM]
,CONVERT(VARCHAR(155) ,[ITS_Srvc_Prov_Name]) AS [ITS_Srvc_Prov_Name]
,CONVERT(VARCHAR(10) ,[ITS_Srvc_Prov_NPI]) AS [ITS_Srvc_Prov_NPI]
,CONVERT(VARCHAR(15) ,[ITS_Srvc_Prov_Zip_Code]) AS [ITS_Srvc_Prov_Zip_Code]
,CONVERT(VARCHAR(4) ,[ITS_Srvc_Prov_Specialty_Code]) AS [ITS_Srvc_Prov_Specialty_Code]
,CONVERT(VARCHAR(70) ,[ITS_Srvc_Prov_Specialty_Desc]) AS [ITS_Srvc_Prov_Specialty_Desc]
,CONVERT(VARCHAR(4) ,[ITS_Srvc_Prov_Type_Code]) AS [ITS_Srvc_Prov_Type_Code]
,CONVERT(VARCHAR(70) ,[ITS_Srvc_Prov_Type_Desc]) AS [ITS_Srvc_Prov_Type_Desc]
,CONVERT(VARCHAR(4) ,[ITS_Srvc_Prov_Host_Plan_Code]) AS [ITS_Srvc_Prov_Host_Plan_Code]
,CONVERT(VARCHAR(70) ,[ITS_Srvc_Prov_Host_Plan_Name]) AS [ITS_Srvc_Prov_Host_Plan_Name]
,CONVERT(VARCHAR(18) ,[ITS_Srvc_Prov_Host_Plan_ID]) AS [ITS_Srvc_Prov_Host_Plan_ID]
,CONVERT(VARCHAR(9) ,[ITS_Bill_Prov_Tax_ID]) AS [ITS_Bill_Prov_Tax_ID]
,CONVERT(VARCHAR(155) ,[ITS_Bill_Prov_Name]) AS [ITS_Bill_Prov_Name]
,CONVERT(VARCHAR(10) ,[ITS_Bill_Prov_NPI]) AS [ITS_Bill_Prov_NPI]
,CONVERT(VARCHAR(4) ,[ITS_Bill_Prov_Host_Plan_Code]) AS [ITS_Bill_Prov_Host_Plan_Code]
,CONVERT(VARCHAR(70) ,[ITS_Bill_Prov_Host_Plan_Name]) AS [ITS_Bill_Prov_Host_Plan_Name]
,CONVERT(VARCHAR(18) ,[ITS_Bill_Prov_Host_Plan_Id]) AS [ITS_Bill_Prov_Host_Plan_Id]
,CONVERT(VARCHAR(100) ,[ITS_Bill_Prov_Address_1]) AS [ITS_Bill_Prov_Address_1]
,CONVERT(VARCHAR(100) ,[ITS_Bill_Prov_Address_2]) AS [ITS_Bill_Prov_Address_2]
,CONVERT(VARCHAR(60) ,[ITS_Bill_Prov_City_Name]) AS [ITS_Bill_Prov_City_Name]
,CONVERT(VARCHAR(4) ,[ITS_Bill_Prov_State_Code]) AS [ITS_Bill_Prov_State_Code]
,CONVERT(VARCHAR(15) ,[ITS_Bill_Prov_Zip_Code]) AS [ITS_Bill_Prov_Zip_Code]
,CONVERT(VARCHAR(20) ,[class_of_risk]) AS [class_of_risk]
,CONVERT(VARCHAR(100) ,[risk_cat_name]) AS [risk_cat_name]
,CONVERT(VARCHAR(255) ,[funding_arrangement]) AS [funding_arrangement]
,CONVERT(VARCHAR(8) ,[Product_ID]) AS [Product_ID]
,CONVERT(VARCHAR(70) ,[Product_Desc]) AS [Product_Desc]
,CONVERT(VARCHAR(20) ,[Payer_ID]) AS [Payer_ID]
,CONVERT(VARCHAR(255) ,[Payer_Name]) AS [Payer_Name]
,CONVERT(VARCHAR(20) ,[Patient_Relationship]) AS [Patient_Relationship_Code]
,CONVERT(VARCHAR(255) ,[Patient_Relationship_Desc]) AS [Patient_Relationship_Desc]
,CONVERT(VARCHAR(20) ,[Discharge_Status]) AS [Discharge_Status]
,CONVERT(MONEY ,[HCRA_Surcharge_Amount]) AS [HCRA_Surcharge_Amount]
,CONVERT(MONEY ,[Risk_Withhold_Amount]) AS [Risk_Withhold_Amount]
INTO AdditionalDataStage
	FROM [ExcellusRaw].[dbo].[VW_ClaimDetails] 
WHERE datadate = @DataDate AND  
[Claim_History_stage] = 'FINAL' 
and RTRIM(LTRIM(SRC_APPL_ADJ_SQNC_NBR)) <> 'IFACETS'


CREATE UNIQUE CLUSTERED INDEX CL_X ON AdditionalDataStage (ClaimRepoClaimNumber,ClaimRepoClaimLineNumber)


SELECT 
ClaimId,
ClaimNumber
INTO #CLAIM
FROM Claim where [FileRequestId] = @FileRequestId
CREATE UNIQUE CLUSTERED INDEX CL_X ON #CLAIM(ClaimId)


SELECT A.*,
ServicelineID,
LineNumber
INTO #FINAL 
 from #Claim a INNER JOIN ServiceLine b on A.ClaimId = B.Claim_id

CREATE UNIQUE CLUSTERED INDEX CL_X ON #FINAL(ClaimId,ServicelineID) 
CREATE UNIQUE INDEX NC_X ON #FINAL (ClaimNumber,LineNumber)




INSERT INTO [dbo].[ServiceLineAdditionalData]
           ([ServiceLineID]
           ,[ClientID]
           ,[File_Type]
           ,[Claim_Adjustment_Number]
           ,[Drug_line]
           ,[CPT4_Procedure_code_Description]
           ,[Insurance_Company_Unique_ID]
           ,[Unique_ID]
           ,[Contract_holders_ID]
           ,[Dependent_Number]
           ,[Other_carrier_paid_amt]
           ,[Claim_Member_Liability]
           ,[Claim_Paid_Date]
           ,[Admitting_Diagnosis]
           ,[Additional_proc_code_1]
           ,[Additional_proc_code_2]
           ,[Additional_proc_code_3]
           ,[Additional_proc_code_4]
           ,[Additional_proc_code_5]
           ,[Place_of_Service_Desc]
           ,[Hosp_Med_Ind]
           ,[Home_Grown_Code]
           ,[Home_Grown_Code_Desc]
           ,[HCPCS_Code]
           ,[HCPCS_Desc]
           ,[Type_of_Service_Code]
           ,[Type_of_Service_Desc]
           ,[Par_Code]
           ,[Par_Desc]
           ,[Servicing_Provider_Tax_Id]
           ,[Adjustment_Indicator]
           ,[Agreement_ID]
           ,[Authorization_Code]
           ,[CLHP_Birth_Wgt]
           ,[Frequency]
           ,[MEDICAL_RECNO]
           ,[Medicare_DRG_Code]
           ,[Mem_Cobra_Indicator]
           ,[Mem_Medicare_Number]
           ,[Mem_Phone]
           ,[Mem_Retirement_Ind]
           ,[Rule]
           ,[Service_Pricing]
           ,[Unit_Days_Allowed]
           ,[DSALW_CODE]
           ,[DSALW_CODE_DESC]
           ,[ADJ_EXPLN_CODE]
           ,[ADJ_EXPLN_CODE_DESC]
           ,[Network_Indicator_Par_Non_Par_System]
           ,[Claim_Type]
           ,[Claim_Received_Date]
           ,[Payee_Code]
           ,[COB_NAME]
           ,[SRC_APPL_CODE]
           ,[SRC_APPL_ADJ_SQNC_NBR]
           ,[GRP_SGMNT_CODE]
           ,[GRP_SGMNT_CODE_DESC]
           ,[FAC_TYPE_CODE]
           ,[FAC_TYPE_CODE_NAME]
           ,[BSNS_SGMNT]
           ,[PROD_CAT_NAME]
           ,[DRG_SYS_ID]
           ,[SOI]
           ,[ROM]
           ,[ITS_Srvc_Prov_Name]
           ,[ITS_Srvc_Prov_NPI]
           ,[ITS_Srvc_Prov_Zip_Code]
           ,[ITS_Srvc_Prov_Specialty_Code]
           ,[ITS_Srvc_Prov_Specialty_Desc]
           ,[ITS_Srvc_Prov_Type_Code]
           ,[ITS_Srvc_Prov_Type_Desc]
           ,[ITS_Srvc_Prov_Host_Plan_Code]
           ,[ITS_Srvc_Prov_Host_Plan_Name]
           ,[ITS_Srvc_Prov_Host_Plan_ID]
           ,[ITS_Bill_Prov_Tax_ID]
           ,[ITS_Bill_Prov_Name]
           ,[ITS_Bill_Prov_NPI]
           ,[ITS_Bill_Prov_Host_Plan_Code]
           ,[ITS_Bill_Prov_Host_Plan_Name]
           ,[ITS_Bill_Prov_Host_Plan_Id]
           ,[ITS_Bill_Prov_Address_1]
           ,[ITS_Bill_Prov_Address_2]
           ,[ITS_Bill_Prov_City_Name]
           ,[ITS_Bill_Prov_State_Code]
           ,[ITS_Bill_Prov_Zip_Code]
           ,[class_of_risk]
           ,[risk_cat_name]
           ,[funding_arrangement]
           ,[Product_ID]
           ,[Product_Desc]
           ,[Payer_ID]
           ,[Payer_Name]
           ,[Patient_Relationship_Code]
           ,[Patient_Relationship_Desc]
           ,[Discharge_Status]
           ,[HCRA_Surcharge_Amount]
           ,[Risk_Withhold_Amount]
           ,[PlanID]
           ,[PlanID_Name]
           ,[Business_Category_Code]
           ,[Business_Category_Description]
           ,[Medicare_Facility_Number_BLNG_PROV]
           ,[HCRA_BLNG_PROV]
           ,[Medicare_Facility_Number_SRVCNG_PROV]
           ,[HCRA_SRVCNG_PROV]
           ,[Micro_Image_ID]
           ,[SCCF_Number]
           ,[Plan_Code]
           ,[Plan_Code_home]
           ,[Additional_proc_code_6]
           ,[Additional_proc_code_7]
           ,[Additional_proc_code_8]
           ,[Additional_proc_code_9]
           ,[Additional_proc_code_10]
           ,[Additional_proc_code_11]
           ,[Additional_proc_code_12]
           ,[Additional_proc_code_13]
           ,[Additional_proc_code_14]
           ,[Additional_proc_code_15]
           ,[Additional_proc_code_16]
           ,[Additional_proc_code_17]
           ,[Additional_proc_code_18]
           ,[Additional_proc_code_19]
           ,[Additional_proc_code_20]
           ,[Additional_proc_code_21]
           ,[Additional_proc_code_22]
           ,[Additional_proc_code_23]
           ,[Additional_proc_code_24]
           ,[Additional_proc_code_25]
           ,[PTNT_ACNT_NBR])





SELECT 
A.[ServiceLineID]													
,3 as [ClientID]														
								
,ERAW.[File_Type]														
,ERAW.[Claim_Adjustment_Number]										
,ERAW.[Drug_line]														
,ERAW.[CPT4_Procedure_code_Description]								
,ERAW.[Insurance_Company_Unique_ID]									
,ERAW.[Unique_ID]														
,ERAW.[Contract_holders_ID]											
,ERAW.[Dependent_Number]												
,ERAW.[Other_carrier_paid_amt]										
,ERAW.[Claim_Member_Liability]										
,ERAW.[Claim_Paid_Date]												
,ERAW.[Admitting_Diagnosis]											
,ERAW.[Additional_proc_code_1]										
,ERAW.[Additional_proc_code_2]										
,ERAW.[Additional_proc_code_3]										
,ERAW.[Additional_proc_code_4]										
,ERAW.[Additional_proc_code_5]										
,ERAW.[Place_of_Service_Desc]											
,ERAW.[Hosp_Med_Ind]													
,ERAW.[Home_Grown_Code]												
,ERAW.[Home_Grown_Code_Desc]											
,ERAW.[HCPCS_Code]													
,ERAW.[HCPCS_Desc]													
,ERAW.[Type_of_Service_Code]											
,ERAW.[Type_of_Service_Desc]											
,ERAW.[Par_Code]														
,ERAW.[Par_Desc]														
,ERAW.[Servicing_Provider_Tax_Id]										
,ERAW.[Adjustment_Indicator]											
,ERAW.[Agreement_ID]													
,ERAW.[Authorization_Code]											
,ERAW.[CLHP_Birth_Wgt]												
,ERAW.[Frequency]														
,ERAW.[MEDICAL_RECNO]													
,ERAW.[Medicare_DRG_Code]												
,ERAW.[Mem_Cobra_Indicator]											
,ERAW.[Mem_Medicare_Number]											
,ERAW.[Mem_Phone]														
,ERAW.[Mem_Retirement_Ind]											
,ERAW.[Rule]															
,ERAW.[Service_Pricing]												
,ERAW.[Unit_Days_Allowed]												
,ERAW.[DSALW_CODE]													
,ERAW.[DSALW_CODE_DESC]												
,ERAW.[ADJ_EXPLN_CODE]												
,ERAW.[ADJ_EXPLN_CODE_DESC]											
,ERAW.[Network_Indicator_Par_Non_Par_System]							
,ERAW.[Claim_Type]													
,ERAW.[Claim_Received_Date]											
,ERAW.[Payee_Code]													
,ERAW.[COB_NAME]														
,ERAW.[SRC_APPL_CODE]													
,ERAW.[SRC_APPL_ADJ_SQNC_NBR]											
,ERAW.[GRP_SGMNT_CODE]												
,ERAW.[GRP_SGMNT_CODE_DESC]											
,ERAW.[FAC_TYPE_CODE]													
,ERAW.[FAC_TYPE_CODE_NAME]											
,ERAW.[BSNS_SGMNT]													
,ERAW.[PROD_CAT_NAME]													
,ERAW.[DRG_SYS_ID]													
,ERAW.[SOI]															
,ERAW.[ROM]															
,ERAW.[ITS_Srvc_Prov_Name]											
,ERAW.[ITS_Srvc_Prov_NPI]												
,ERAW.[ITS_Srvc_Prov_Zip_Code]										
,ERAW.[ITS_Srvc_Prov_Specialty_Code]									
,ERAW.[ITS_Srvc_Prov_Specialty_Desc]									
,ERAW.[ITS_Srvc_Prov_Type_Code]										
,ERAW.[ITS_Srvc_Prov_Type_Desc]										
,ERAW.[ITS_Srvc_Prov_Host_Plan_Code]									
,ERAW.[ITS_Srvc_Prov_Host_Plan_Name]									
,ERAW.[ITS_Srvc_Prov_Host_Plan_ID]									
,ERAW.[ITS_Bill_Prov_Tax_ID]											
,ERAW.[ITS_Bill_Prov_Name]											
,ERAW.[ITS_Bill_Prov_NPI]												
,ERAW.[ITS_Bill_Prov_Host_Plan_Code]									
,ERAW.[ITS_Bill_Prov_Host_Plan_Name]									
,ERAW.[ITS_Bill_Prov_Host_Plan_Id]									
,ERAW.[ITS_Bill_Prov_Address_1]										
,ERAW.[ITS_Bill_Prov_Address_2]										
,ERAW.[ITS_Bill_Prov_City_Name]										
,ERAW.[ITS_Bill_Prov_State_Code]										
,ERAW.[ITS_Bill_Prov_Zip_Code]										
,ERAW.[class_of_risk]													
,ERAW.[risk_cat_name]													
,ERAW.[funding_arrangement]											
,ERAW.[Product_ID]													
,ERAW.[Product_Desc]													
,ERAW.[Payer_ID]														
,ERAW.[Payer_Name]													
,ERAW.[Patient_Relationship_Code]												
,ERAW.[Patient_Relationship_Desc]										
,ERAW.[Discharge_Status]												
,ERAW.[HCRA_Surcharge_Amount]											
,ERAW.[Risk_Withhold_Amount]
,DRG.[PlanID]														
,DRG.[PlanID_Name]													
,DRG.[Business_Category_Code]										
,DRG.[Business_Category_Description]									
,DRG.[Medicare_Facility_Number_BLNG_PROV]							
,DRG.[HCRA_BLNG_PROV]												
,DRG.[Medicare_Facility_Number_SRVCNG_PROV]							
,DRG.[HCRA_SRVCNG_PROV]												
,DRG.[Micro_Image_ID]												
,DRG.[SCCF_Number]													
,DRG.[Plan_Code]														
,DRG.[Plan_Code_home]												
--[Additional_Diagnosis_9]										
--[Additional_Diagnosis_10]										
--[Additional_Diagnosis_11]										
--[Additional_Diagnosis_12]										
--[Additional_Diagnosis_13]										
--[Additional_Diagnosis_14]										
--[Additional_Diagnosis_15]										
--[Additional_Diagnosis_16]										
--[Additional_Diagnosis_17]										
--[Additional_Diagnosis_18]										
--[Additional_Diagnosis_19]										
--[Additional_Diagnosis_20]										
--[Additional_Diagnosis_21]										
--[Additional_Diagnosis_22]										
--[Additional_Diagnosis_23]										
--[Additional_Diagnosis_24]										
,DRG.[Additional_proc_code_6]										
,DRG.[Additional_proc_code_7]										
,DRG.[Additional_proc_code_8]										
,DRG.[Additional_proc_code_9]										
,DRG.[Additional_proc_code_10]										
,DRG.[Additional_proc_code_11]										
,DRG.[Additional_proc_code_12]										
,DRG.[Additional_proc_code_13]										
,DRG.[Additional_proc_code_14]										
,DRG.[Additional_proc_code_15]										
,DRG.[Additional_proc_code_16]										
,DRG.[Additional_proc_code_17]										
,DRG.[Additional_proc_code_18]										
,DRG.[Additional_proc_code_19]										
,DRG.[Additional_proc_code_20]										
,DRG.[Additional_proc_code_21]										
,DRG.[Additional_proc_code_22]										
,DRG.[Additional_proc_code_23]										
,DRG.[Additional_proc_code_24]										
,DRG.[Additional_proc_code_25]										
,DRG.[PTNT_ACNT_NBR]																								
									



FROM 
#FINAL A  
INNER JOIN AdditionalDataStage ERAW ON A.ClaimNumber = ERAW.ClaimRepoClaimNumber 
and A.LineNumber  = ERAW.ClaimRepoClaimLineNumber 
LEFT JOIN [dbo].[ServiceLineDRG] DRG on A.ServicelineID = DRG.ServicelineID

DROP TABLE #FINAL
DROP TABLE #CLAIM
DROP TABLE AdditionalDataStage
END



;