
CREATE view [dbo].[claim_vw] 
as
Select 
ClaimId,
ClientId,
FileRequestId,
cast(ClaimKey as varchar (255) ) as ClaimKey,
cast(ClaimNumber as varchar (255) ) as ClaimNumber,
cast(AuditState as varchar (255) ) as AuditState,
cast(AttendingProviderQualifierCode as varchar (255) ) as AttendingProviderQualifierCode,
cast(OperatingProviderQualifierCode as varchar (255) ) as OperatingProviderQualifierCode,
cast(PatientAccountNumber as varchar (255) ) as PatientAccountNumber,
cast(MedicalRecordNumber as varchar (255) ) as MedicalRecordNumber,
cast(TypeOfBill as varchar (255) ) as TypeOfBill,
cast(AccidentState as varchar (255) ) as AccidentState,
cast(AdmittingDiagnosisCode as varchar (255) ) as AdmittingDiagnosisCode,
cast(PrincipalDiagnosisCode as varchar (255) ) as PrincipalDiagnosisCode,
cast(ProspectivePaymentSystemCode as varchar (255) ) as ProspectivePaymentSystemCode,
AdmissionDate,
DischargeDate,
AdmissionHour,
cast(PriorityOfVisit as varchar (255) ) as PriorityOfVisit,
cast(AdmissionSource as varchar (255) ) as AdmissionSource,
cast(PrincipalProcedureCode as varchar (255) ) as PrincipalProcedureCode,
PrincipalProcedureCodeDate,
cast(FormType as varchar (255) ) as FormType,
cast(ClaimType as varchar (255) ) as ClaimType,
cast(Remarks as varchar (255) ) as Remarks,
cast(ResponsibleParties as varchar (255) ) as ResponsibleParties,
cast(ExternalCauseOfInjury1 as varchar (255) ) as ExternalCauseOfInjury1,
cast(ExternalCauseOfInjury2 as varchar (255) ) as ExternalCauseOfInjury2,
cast(ExternalCauseOfInjury3 as varchar (255) ) as ExternalCauseOfInjury3,
cast(OtherProviderNPI1 as varchar (255) ) as OtherProviderNPI1,
cast(OtherProviderQualifierCode1 as varchar (255) ) as OtherProviderQualifierCode1,
cast(OtherProviderNPI2 as varchar (255) ) as OtherProviderNPI2,
cast(OtherProviderQualifierCode2 as varchar (255) ) as OtherProviderQualifierCode2,
cast(OtherProviderNPI3 as varchar (255) ) as OtherProviderNPI3,
cast(OtherProviderQualifierCode3 as varchar (255) ) as OtherProviderQualifierCode3,
PaidDate,
cast(DischargeStatus as varchar (255) ) as DischargeStatus,
DateOfCurrentIllness,
cast(DateOfCurrentIllnessQualifierCode as varchar (255) ) as DateOfCurrentIllnessQualifierCode,
OtherDateOfCurrentIllness,
cast(OtherDateOfCurrentIllnessQualifierCode as varchar (255) ) as OtherDateOfCurrentIllnessQualifierCode,
AmountPaid,
BeneficiaryUnableToWorkStartDate,
BeneficiaryUnableToWorkEndDate,
cast(ReferringProviderOrOtherSourceName as varchar (255) ) as ReferringProviderOrOtherSourceName,
cast(ReferringProviderOrOtherSourceOtherQualifierCode as varchar (255) ) as ReferringProviderOrOtherSourceOtherQualifierCode,
cast(ReferringProviderOrOtherSourceOtherIdNumber as varchar (255) ) as ReferringProviderOrOtherSourceOtherIdNumber,
BeneficiaryDischargeHour,
cast(BeneficiaryDischargeStatus as varchar (255) ) as BeneficiaryDischargeStatus,
HospitalizationStartDate,
HospitalizationEndDate,
cast(ClaimCodes as varchar (255) ) as ClaimCodes,
OutsideLab,
OutsideLabCharges,
cast(ResubmissionCode as varchar (255) ) as ResubmissionCode,
cast(OriginalReferenceNumber as varchar (255) ) as OriginalReferenceNumber,
cast(PriorAuthorizationNumber as varchar (255) ) as PriorAuthorizationNumber,
IsThereOtherHealthBenefitPlan,
ConditionRelatedToEmployment,
ConditionRelatedToAutoAccident,
cast(ConditionRelatedToAutoAccidentState as varchar (255) ) as ConditionRelatedToAutoAccidentState,
ConditionRelatedToOther,
cast(BeneficiarysOrAuthorizedSignature as varchar (255) ) as BeneficiarysOrAuthorizedSignature,
BeneficiarysOrAuthorizedSignatureDate,
cast(InsuredOrAuthorizedSignature as varchar (255) ) as InsuredOrAuthorizedSignature,
cast(SignatureOfPhysicianOrSupplier as varchar (255) ) as SignatureOfPhysicianOrSupplier,
SignatureOfPhysicianOrSupplierDate,
cast(ServiceFacility as varchar (255) ) as ServiceFacility,
TotalCharge,
cast(IcdIndicator as varchar (255) ) as IcdIndicator,
cast(DiagnosticRelatedGroup as varchar (255) ) as DiagnosticRelatedGroup,
cast(AdditionalDataJson as varchar (MAX) ) as AdditionalDataJson,
cast(CreatedBy as varchar (255) ) as CreatedBy,
CreatedDate,
cast(LastUpdatedBy as varchar (255) ) as LastUpdatedBy,
LastUpdatedDate,
Beneficiary_id,
BillingProvider_id,
AttendingProvider_id,
OperatingProvider_id,
Payer1_id,
Payer2_id,
Payer3_id,
ReferringProviderOrOtherSourceProvider_id,
cast(BillingProviderMedicareFacilityNumber as varchar (255) ) as BillingProviderMedicareFacilityNumber,
cast(AttendingProviderMedicareFacilityNumber as varchar (255) ) as AttendingProviderMedicareFacilityNumber,
SeverityOfIllness,
RiskOfMortality
from dbo.claim
