CREATE view serviceline_vw
as

select 
ServiceLineId,
cast(LineNumber as varchar (255) ) as LineNumber,
cast(RevenueCode as varchar (255) ) as RevenueCode,
cast(SupplementalRevenueCode as varchar (255) ) as SupplementalRevenueCode,
cast(RevenueDescription as varchar (255) ) as RevenueDescription,
cast(SupplementalRevenueDescription as varchar (255) ) as SupplementalRevenueDescription,
cast(PlaceOfService as varchar (255) ) as PlaceOfService,
cast(SupplementalPlaceOfService as varchar (255) ) as SupplementalPlaceOfService,
cast(EMG as varchar (255) ) as EMG,
cast(SupplementalEMG as varchar (255) ) as SupplementalEMG,
cast(ProcedureCode as varchar (255) ) as ProcedureCode,
cast(SupplementalProcedureCode as varchar (255) ) as SupplementalProcedureCode,
DateOfServiceStartDate,
SupplementalDateOfServiceStartDate,
DateOfServiceEndDate,
SupplementalDateOfServiceEndDate,
Units,
UnitsAllowed,
cast(SupplementalUnits as varchar (255) ) as SupplementalUnits,
cast(EPSDTFamilyPlan as varchar (255) ) as EPSDTFamilyPlan,
cast(SupplementalEPSDTFamilyPlan as varchar (255) ) as SupplementalEPSDTFamilyPlan,
TotalCharges,
SupplementalTotalCharges,
NonCoveredCharges,
SupplementalNonCoveredCharges,
cast(ModifierCode1 as varchar (255) ) as ModifierCode1,
cast(ModifierCode2 as varchar (255) ) as ModifierCode2,
cast(ModifierCode3 as varchar (255) ) as ModifierCode3,
cast(ModifierCode4 as varchar (255) ) as ModifierCode4,
AllowedAmount,
CopayAmount,
CoinsuranceAmount,
DeductibleAmount,
PaidAmount,
cast(AdditionalDataJson as varchar (MAX) ) as AdditionalDataJson,
Claim_id,
BillingProvider_id,
AttendingProvider_id,
SupplementalProvider_id
from dbo.serviceline