

CREATE PROCEDURE [dbo].usp_DAILY_AUDIT_DB_BACK_UP_PARAM @DBLIST VARCHAR(MAX)= NULL
AS 
BEGIN 

IF @DBLIST IS NULL
BEGIN

SET @DBLIST = 'APAudit,APShared,APMedia,APSSNSSB,IONSSB'

END


DECLARE @SQL NVARCHAR(MAX)

;WITH DBS AS  (
select LEFT(@DBLIST, CHARINDEX(',',@DBLIST+',')-1) DB,
    STUFF(@DBLIST, 1, CHARINDEX(',',@DBLIST+','), '') as LIST

union all
select  LEFT(LIST, CHARINDEX(',',LIST+',')-1),
    STUFF(LIST, 1, CHARINDEX(',',LIST+','), '')
FROM DBS
where LIST > ''
)


SELECT @SQL = 
STUFF( (
SELECT REPLACE(REPLACE(
'---' + CHAR(10) + 
'BACKUP DATABASE $DB$ TO DISK = ''\\lv-pdsqlbi01\ExcellusPickup\DB_Backups\$DATESTAMP$_$DB$.BAK''   WITH FORMAT,COMPRESSION;'
,'$DB$',DB),'$DATESTAMP$',REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(50),GETDATE(),120),' ',''),':',''),'-',''))
FROM DBS
FOR XML PATH('')), 1, 1, '')

PRINT @SQL
EXECUTE SP_EXECUTESQL @SQL

END
