CREATE TABLE [dbo].[AdditionalDataStage] (
    [ClaimRepoClaimNumber]                 NVARCHAR (255)  NULL,
    [ClaimRepoClaimLineNumber]             NVARCHAR (255)  NULL,
    [File_Type]                            VARCHAR (2)     NULL,
    [Claim_Adjustment_Number]              VARCHAR (8)     NULL,
    [Drug_line]                            VARCHAR (1)     NULL,
    [CPT4_Procedure_code_Description]      VARCHAR (70)    NULL,
    [Insurance_Company_Unique_ID]          VARCHAR (7)     NULL,
    [Unique_ID]                            VARCHAR (20)    NULL,
    [Contract_holders_ID]                  VARCHAR (30)    NULL,
    [Dependent_Number]                     VARCHAR (3)     NULL,
    [Other_carrier_paid_amt]               MONEY           NULL,
    [Claim_Member_Liability]               MONEY           NULL,
    [Claim_Paid_Date]                      DATETIME        NULL,
    [Admitting_Diagnosis]                  VARCHAR (7)     NULL,
    [Additional_proc_code_1]               VARCHAR (20)    NULL,
    [Additional_proc_code_2]               VARCHAR (20)    NULL,
    [Additional_proc_code_3]               VARCHAR (20)    NULL,
    [Additional_proc_code_4]               VARCHAR (20)    NULL,
    [Additional_proc_code_5]               VARCHAR (20)    NULL,
    [Place_of_Service_Desc]                VARCHAR (255)   NULL,
    [Hosp_Med_Ind]                         VARCHAR (4)     NULL,
    [Home_Grown_Code]                      VARCHAR (9)     NULL,
    [Home_Grown_Code_Desc]                 VARCHAR (250)   NULL,
    [HCPCS_Code]                           VARCHAR (9)     NULL,
    [HCPCS_Desc]                           VARCHAR (150)   NULL,
    [Type_of_Service_Code]                 VARCHAR (4)     NULL,
    [Type_of_Service_Desc]                 VARCHAR (70)    NULL,
    [Par_Code]                             VARCHAR (1)     NULL,
    [Par_Desc]                             VARCHAR (75)    NULL,
    [Servicing_Provider_Tax_Id]            VARCHAR (18)    NULL,
    [Adjustment_Indicator]                 VARCHAR (70)    NULL,
    [Agreement_ID]                         VARCHAR (30)    NULL,
    [Authorization_Code]                   VARCHAR (18)    NULL,
    [CLHP_Birth_Wgt]                       DECIMAL (19, 2) NULL,
    [Frequency]                            VARCHAR (20)    NULL,
    [MEDICAL_RECNO]                        VARCHAR (16)    NULL,
    [Medicare_DRG_Code]                    VARCHAR (3)     NULL,
    [Mem_Cobra_Indicator]                  VARCHAR (1)     NULL,
    [Mem_Medicare_Number]                  VARCHAR (12)    NULL,
    [Mem_Phone]                            VARCHAR (30)    NULL,
    [Mem_Retirement_Ind]                   VARCHAR (1)     NULL,
    [Rule]                                 VARCHAR (4)     NULL,
    [Service_Pricing]                      VARCHAR (4)     NULL,
    [Unit_Days_Allowed]                    MONEY           NULL,
    [DSALW_CODE]                           VARCHAR (20)    NULL,
    [DSALW_CODE_DESC]                      VARCHAR (255)   NULL,
    [ADJ_EXPLN_CODE]                       VARCHAR (20)    NULL,
    [ADJ_EXPLN_CODE_DESC]                  VARCHAR (255)   NULL,
    [Network_Indicator_Par_Non_Par_System] VARCHAR (75)    NULL,
    [Claim_Type]                           VARCHAR (75)    NULL,
    [Claim_Received_Date]                  DATETIME        NULL,
    [Payee_Code]                           VARCHAR (75)    NULL,
    [COB_NAME]                             VARCHAR (75)    NULL,
    [SRC_APPL_CODE]                        VARCHAR (20)    NULL,
    [SRC_APPL_ADJ_SQNC_NBR]                VARCHAR (5)     NULL,
    [GRP_SGMNT_CODE]                       VARCHAR (4)     NULL,
    [GRP_SGMNT_CODE_DESC]                  VARCHAR (255)   NULL,
    [FAC_TYPE_CODE]                        VARCHAR (20)    NULL,
    [FAC_TYPE_CODE_NAME]                   VARCHAR (255)   NULL,
    [BSNS_SGMNT]                           VARCHAR (255)   NULL,
    [PROD_CAT_NAME]                        VARCHAR (255)   NULL,
    [DRG_SYS_ID]                           VARCHAR (20)    NULL,
    [SOI]                                  VARCHAR (4)     NULL,
    [ROM]                                  VARCHAR (4)     NULL,
    [ITS_Srvc_Prov_Name]                   VARCHAR (155)   NULL,
    [ITS_Srvc_Prov_NPI]                    VARCHAR (10)    NULL,
    [ITS_Srvc_Prov_Zip_Code]               VARCHAR (15)    NULL,
    [ITS_Srvc_Prov_Specialty_Code]         VARCHAR (4)     NULL,
    [ITS_Srvc_Prov_Specialty_Desc]         VARCHAR (70)    NULL,
    [ITS_Srvc_Prov_Type_Code]              VARCHAR (4)     NULL,
    [ITS_Srvc_Prov_Type_Desc]              VARCHAR (70)    NULL,
    [ITS_Srvc_Prov_Host_Plan_Code]         VARCHAR (4)     NULL,
    [ITS_Srvc_Prov_Host_Plan_Name]         VARCHAR (70)    NULL,
    [ITS_Srvc_Prov_Host_Plan_ID]           VARCHAR (18)    NULL,
    [ITS_Bill_Prov_Tax_ID]                 VARCHAR (9)     NULL,
    [ITS_Bill_Prov_Name]                   VARCHAR (155)   NULL,
    [ITS_Bill_Prov_NPI]                    VARCHAR (10)    NULL,
    [ITS_Bill_Prov_Host_Plan_Code]         VARCHAR (4)     NULL,
    [ITS_Bill_Prov_Host_Plan_Name]         VARCHAR (70)    NULL,
    [ITS_Bill_Prov_Host_Plan_Id]           VARCHAR (18)    NULL,
    [ITS_Bill_Prov_Address_1]              VARCHAR (100)   NULL,
    [ITS_Bill_Prov_Address_2]              VARCHAR (100)   NULL,
    [ITS_Bill_Prov_City_Name]              VARCHAR (60)    NULL,
    [ITS_Bill_Prov_State_Code]             VARCHAR (4)     NULL,
    [ITS_Bill_Prov_Zip_Code]               VARCHAR (15)    NULL,
    [class_of_risk]                        VARCHAR (20)    NULL,
    [risk_cat_name]                        VARCHAR (100)   NULL,
    [funding_arrangement]                  VARCHAR (255)   NULL,
    [Product_ID]                           VARCHAR (8)     NULL,
    [Product_Desc]                         VARCHAR (70)    NULL,
    [Payer_ID]                             VARCHAR (20)    NULL,
    [Payer_Name]                           VARCHAR (255)   NULL,
    [Patient_Relationship_Code]            VARCHAR (20)    NULL,
    [Patient_Relationship_Desc]            VARCHAR (255)   NULL,
    [Discharge_Status]                     VARCHAR (20)    NULL,
    [HCRA_Surcharge_Amount]                MONEY           NULL,
    [Risk_Withhold_Amount]                 MONEY           NULL
);

