CREATE TABLE [dbo].[ProviderAdditionalData] (
    [ProviderId]                     INT                                   NOT NULL,
    [ClientID]                       INT                                   NOT NULL,
    [AdditionalData_Columnset]       XML COLUMN_SET FOR ALL_SPARSE_COLUMNS,
    [File_Type]                      VARCHAR (1) SPARSE                    NULL,
    [Filler_1]                       VARCHAR (5) SPARSE                    NULL,
    [Filler_2]                       VARCHAR (5) SPARSE                    NULL,
    [Address_3]                      VARCHAR (100) SPARSE                  NULL,
    [Insurance_Company_Unique_ID]    VARCHAR (7) SPARSE                    NULL,
    [Specialty_Code]                 VARCHAR (4) SPARSE                    NULL,
    [Specialty_Description]          VARCHAR (100) SPARSE                  NULL,
    [SRC_APPL_CODE]                  VARCHAR (20) SPARSE                   NULL,
    [PROV_ENTITY_CODE]               VARCHAR (20) SPARSE                   NULL,
    [PROV_ENTITY_DESCRIPTION]        VARCHAR (100) SPARSE                  NULL,
    [PROV_TYPE_DESCRIPTION]          VARCHAR (100) SPARSE                  NULL,
    [PROV_NYS_SPECIALTY_CODE]        VARCHAR (20) SPARSE                   NULL,
    [PROV_NYS_SPECIALTY_DESCRIPTION] VARCHAR (100) SPARSE                  NULL,
    [PROVIDER_DEA]                   VARCHAR (12) SPARSE                   NULL,
    [PROVIDER_TAX_ID_SUFFIX]         VARCHAR (5) SPARSE                    NULL,
    [PROVIDER_NUM]                   VARCHAR (12) SPARSE                   NULL,
    [PROVIDER_NUM_SUFFIX]            VARCHAR (5) SPARSE                    NULL,
    [PROVIDER_NUM_QUALIFIER]         VARCHAR (2) SPARSE                    NULL,
    [SECURITY_CODE]                  VARCHAR (2) SPARSE                    NULL,
    [NETWORK_CODE]                   VARCHAR (3) SPARSE                    NULL,
    [PROVIDER_FACILITY_NAME]         VARCHAR (255) SPARSE                  NULL,
    [PROVIDER_FACILITY_NUM]          VARCHAR (12) SPARSE                   NULL,
    [PROVIDER_COUNTY]                VARCHAR (50) SPARSE                   NULL,
    [PROVIDER_COUNTRY]               VARCHAR (2) SPARSE                    NULL,
    [PROVIDER_REGION]                VARCHAR (4) SPARSE                    NULL,
    [PROV_SPECIALTY_CD_1]            VARCHAR (9) SPARSE                    NULL,
    [PROV_SPECIALTY_CD_2]            VARCHAR (9) SPARSE                    NULL,
    [PROVIDER_TYPE]                  VARCHAR (2) SPARSE                    NULL,
    [WATCH_CD]                       VARCHAR (1) SPARSE                    NULL,
    [LATEST_UPDATE_DATE]             DATETIME SPARSE                       NULL,
    [PROV_USER_DEF_01]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_02]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_03]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_04]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_05]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_06]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_07]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_08]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_09]               VARCHAR (50) SPARSE                   NULL,
    [PROV_USER_DEF_10]               VARCHAR (50) SPARSE                   NULL,
    [PROVIDER_ENTITY]                VARCHAR (1) SPARSE                    NULL,
    [SPECIALTY_1]                    VARCHAR (4) SPARSE                    NULL,
    [SPECIALTY_2]                    VARCHAR (4) SPARSE                    NULL,
    [TAXONOMY_CODE]                  VARCHAR (12) SPARSE                   NULL,
    [PROVIDER_FIRST_NAME]            VARCHAR (15) SPARSE                   NULL,
    [PROVIDER_MIDDLE_INITIAL]        VARCHAR (1) SPARSE                    NULL,
    [PROVIDER_LAST_NAME]             VARCHAR (35) SPARSE                   NULL,
    [PROVIDER_TITLE]                 VARCHAR (10) SPARSE                   NULL,
    [PROVIDER_GENDER]                VARCHAR (1) SPARSE                    NULL,
    [COMMON_PRACTITIONER_ID]         VARCHAR (12) SPARSE                   NULL,
    [PRACTITIONER_GROUP_ID]          VARCHAR (12) SPARSE                   NULL,
    [PRACTITIONER_GROUP_NAME]        VARCHAR (50) SPARSE                   NULL,
    [DEA_NUMBER]                     VARCHAR (15) SPARSE                   NULL,
    [LICENSE_NUMBER]                 VARCHAR (15) SPARSE                   NULL,
    [OPERATING_CERTIFICATE_ID]       VARCHAR (15) SPARSE                   NULL,
    [PARTICIPATING_FACILITY_ID]      VARCHAR (15) SPARSE                   NULL,
    [MEDS_ID]                        VARCHAR (8) SPARSE                    NULL,
    [MEDICAID_NUMBER]                VARCHAR (15) SPARSE                   NULL,
    [EFFECTIVE_DATE]                 DATETIME SPARSE                       NULL,
    [TERMINATION_DATE]               DATETIME SPARSE                       NULL,
    [EMAIL]                          VARCHAR (40) SPARSE                   NULL,
    [PRACTICE_COUNTY]                VARCHAR (20) SPARSE                   NULL,
    [PRACTICE_COUNTRY]               VARCHAR (4) SPARSE                    NULL,
    [PRACTICE_FAX]                   VARCHAR (20) SPARSE                   NULL,
    [MAILING_ADDRESS_1]              VARCHAR (40) SPARSE                   NULL,
    [MAILING_ADDRESS_2]              VARCHAR (40) SPARSE                   NULL,
    [MAILING_CITY]                   VARCHAR (19) SPARSE                   NULL,
    [MAILING_STATE]                  VARCHAR (2) SPARSE                    NULL,
    [MAILING_POSTAL_CODE]            VARCHAR (11) SPARSE                   NULL,
    [MAILING_COUNTY]                 VARCHAR (20) SPARSE                   NULL,
    [MAILING_COUNTRY]                VARCHAR (4) SPARSE                    NULL,
    [MAILING_PHONE]                  VARCHAR (20) SPARSE                   NULL,
    [MAILING_FAX]                    VARCHAR (20) SPARSE                   NULL,
    [REMITTANCE_ADDRESS_1]           VARCHAR (40) SPARSE                   NULL,
    [REMITTANCE_ADDRESS_2]           VARCHAR (40) SPARSE                   NULL,
    [REMITTANCE_CITY]                VARCHAR (19) SPARSE                   NULL,
    [REMITTANCE_STATE]               VARCHAR (2) SPARSE                    NULL,
    [REMITTANCE_POSTAL_CODE]         VARCHAR (11) SPARSE                   NULL,
    [REMITTANCE_COUNTY]              VARCHAR (20) SPARSE                   NULL,
    [REMITTANCE_COUNTRY]             VARCHAR (4) SPARSE                    NULL,
    [REMITTANCE_PHONE]               VARCHAR (20) SPARSE                   NULL,
    [REMITTANCE_FAX]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_1]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_2]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_3]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_4]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_5]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_6]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_7]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_8]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_9]                 VARCHAR (20) SPARSE                   NULL,
    [PRV_USER_DEF_10]                VARCHAR (20) SPARSE                   NULL,
    [PRV_FILLER]                     VARCHAR (255) SPARSE                  NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [UNQ_ProviderAdditionalData]
    ON [dbo].[ProviderAdditionalData]([ProviderId] ASC);

